#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

	if [ -d /usr/share/plymouth/themes/black ]; then
        update-alternatives \
            --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
            /usr/share/plymouth/themes/black/black.plymouth 400

        update-alternatives \
            --set default.plymouth \
            /usr/share/plymouth/themes/black/black.plymouth

        update-initramfs -u
    fi

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0