#!/bin/sh

set -e

case "$1" in
    remove|deconfigure|failed-upgrade|purge)
        if command -v update-alternatives >/dev/null 2>&1; then
            if [ -d /usr/share/plymouth/themes/bgrt-hamonikr ]; then
                update-alternatives --remove \
                    default.plymouth /usr/share/plymouth/themes/bgrt-hamonikr/bgrt-hamonikr.plymouth || true
            fi
            if [ -d /usr/share/plymouth/themes/hamonikr-default ]; then
                update-alternatives --remove \
                    default.plymouth /usr/share/plymouth/themes/hamonikr-default/hamonikr-default.plymouth || true
            fi
            if [ -d /usr/share/plymouth/themes/hamonikr-black ]; then
                update-alternatives --remove \
                    default.plymouth /usr/share/plymouth/themes/hamonikr-black/hamonikr-black.plymouth || true
            fi
            if [ -d /usr/share/plymouth/themes/hamonikr-flame ]; then
                update-alternatives --remove \
                    default.plymouth /usr/share/plymouth/themes/hamonikr-flame/hamonikr-flame.plymouth || true
            fi
        fi
    ;;
    
    upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
