#!/bin/sh

set -e

case "$1" in
    remove|purge)
        update-alternatives --remove \
            default.plymouth /usr/share/plymouth/themes/bgrt-hamonikr/bgrt-hamonikr.plymouth || true
        update-alternatives --remove \
            default.plymouth /usr/share/plymouth/themes/hamonikr-default/hamonikr-default.plymouth || true
        update-alternatives --remove \
            default.plymouth /usr/share/plymouth/themes/hamonikr-black/hamonikr-black.plymouth || true
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
