#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        # fix for debian 12
        if [ -d /usr/share/desktop-base/debian-logos ]; then
            echo "Move debian logo..."
            if [ ! -d /usr/share/desktop-base/debian-logos/bak ]; then
                echo "Create /usr/share/desktop-base/debian-logos/bak..."
                mkdir -p /usr/share/desktop-base/debian-logos/bak
            fi
            if ls /usr/share/desktop-base/debian-logos/logo-text* 1> /dev/null 2>&1; then
                echo "Move /usr/share/desktop-base/debian-logos/logo-text* ..."
                mv /usr/share/desktop-base/debian-logos/logo-text* /usr/share/desktop-base/debian-logos/bak
            fi
        fi

        if [ -d /usr/share/plymouth/themes/bgrt-hamonikr ]; then
            if command -v update-alternatives >/dev/null 2>&1; then
                update-alternatives \
                    --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                    /usr/share/plymouth/themes/bgrt-hamonikr/bgrt-hamonikr.plymouth 300
            fi
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr-default ]; then
            if command -v update-alternatives >/dev/null 2>&1; then
                update-alternatives \
                    --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                    /usr/share/plymouth/themes/hamonikr-default/hamonikr-default.plymouth 300
            fi
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr-flame ]; then
            if command -v update-alternatives >/dev/null 2>&1; then
                update-alternatives \
                    --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                    /usr/share/plymouth/themes/hamonikr-flame/hamonikr-flame.plymouth 300
            fi
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr-black ]; then
            if command -v update-alternatives >/dev/null 2>&1; then
                update-alternatives \
                    --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                    /usr/share/plymouth/themes/hamonikr-black/hamonikr-black.plymouth 300
            fi
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr ]; then
            if command -v update-alternatives >/dev/null 2>&1; then
                update-alternatives \
                    --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                    /usr/share/plymouth/themes/hamonikr/hamonikr.plymouth 400
            fi
        fi

        # Set default theme
        if command -v update-alternatives >/dev/null 2>&1; then
            update-alternatives \
                --set default.plymouth \
                /usr/share/plymouth/themes/hamonikr/hamonikr.plymouth
        fi

        if command -v update-initramfs >/dev/null 2>&1; then
            update-initramfs -u
        fi

        # pi5, LMDE
        if command -v plymouth-set-default-theme >/dev/null 2>&1; then
            plymouth-set-default-theme -R hamonikr-flame || true
        fi

        # Update grub title
        /etc/hamonikr/adjustments/10-adjust-grub-title.execute || true

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
