#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        # fix for debian 12
        if [ -d /usr/share/desktop-base/debian-logos ]; then
            echo "Move debian logo..."
            if [ ! -d /usr/share/desktop-base/debian-logos/bak ]; then
                mkdir /usr/share/desktop-base/debian-logos/bak
            fi
            mv /usr/share/desktop-base/debian-logos/logo-text* /usr/share/desktop-base/debian-logos/bak || true
        fi

        if [ -d /usr/share/plymouth/themes/bgrt-hamonikr ]; then
            update-alternatives \
                --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                /usr/share/plymouth/themes/bgrt-hamonikr/bgrt-hamonikr.plymouth 500
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr-default ]; then
            update-alternatives \
                --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                /usr/share/plymouth/themes/hamonikr-default/hamonikr-default.plymouth 500
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr-flame ]; then
            update-alternatives \
                --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                /usr/share/plymouth/themes/hamonikr-flame/hamonikr-flame.plymouth 500
        fi

        if [ -d /usr/share/plymouth/themes/hamonikr-black ]; then
            update-alternatives \
                --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                /usr/share/plymouth/themes/hamonikr-black/hamonikr-black.plymouth 600

        fi

        update-alternatives \
            --set default.plymouth \
            /usr/share/plymouth/themes/hamonikr-black/hamonikr-black.plymouth

        if [ -x /usr/sbin/plymouth-set-default-theme ]; then
            plymouth-set-default-theme hamonikr-black
        fi  

        update-initramfs -u
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0